### ISSUE TITLE
Hack Deck Component FF & Safari style bug

### ISSUE THREAD

**Issue by evitolins** [staticshowdown/ss15-rhythm#22]
Seems that using :nth-child is causing issues in both Firefox and Safari

## Current Broken Code
```css
// Card Stack
#container :nth-child(1){position: absolute; top: 0px; left: 0px; z-index:5;  display: inherit;}
#container :nth-child(2){position: absolute; top: 2px; left: 1px; z-index:4;  display: inherit;}
#container :nth-child(3){position: absolute; top: 4px; left: 2px; z-index:3;  display: inherit;}
#container :nth-child(4){position: absolute; top: 6px; left: 3px; z-index:2;  display: inherit;}
#container :nth-child(5){position: absolute; top: 8px; left: 4px; z-index:1;  display: inherit;}

// Position and hide rest of cards
hack-card-admin {
    position: absolute; top: 0; left: 8px; z-index:1; display: none;
}
```

## Working in all browsers, but shows bottom card on top.
```css
// Position and hide rest of cards
hack-card-admin {
    position: absolute; top: 0; left: 8px;
}
```
